### ISSUE TITLE
重连之后未重新订阅已经订阅的topic

### ISSUE THREAD

**Issue by whu12yz** [tennessine/paho.mqtt.wxapp#10]
socket断掉之后重连，看看能否在订阅的时候做一级缓存，重连的时候可以自动订阅之前已经订阅的topic

**Comment by tennessine** [comment]
@whu12yz 你可以用cleansession false登录，然后topic就是持久订阅了，移动端断线重连太频繁了，我觉得持久订阅比较好。

**Comment by whu12yz** [comment]
小程序隐藏到后台，然后切换网络环境之后，再回到小程序，不会自动重连。有解决办法麽～

**Comment by tennessine** [comment]
@whu12yz 是不是可以在小程序生命周期函数onShow里判断网络状态，如果和之前保存的不一样，就重连

**Comment by tennessine** [comment]
# ****
