### ISSUE TITLE
小程序客户端设置Sec-WebSocket-Protocol mqtt

### ISSUE THREAD

**Issue by BingxingXu** [tennessine/paho.mqtt.wxapp#11]
>  mosquitto需要使用nginx反向代理，因为小程序不传递"Sec-WebSocket-Protocol mqtt" header, 可以参考这篇文章 https://zhuanlan.zhihu.com/p/24823848

  微信websocket支持子协议组，可以直接在客户端添加protocols， 而不需要在nginx上设置 ` proxy_set_header Sec-WebSocket-Protocol mqtt`
```js
 wx.connectSocket({
        url: wsurl,
        protocols: ['mqtt']
    });
```
另外： 直接写在在wx.connectSocket({ header: XXXX, ... })里面是不行的，而且`mqtt`必须是小写 ╭(╯^╰)╮
测试broker: emqttd, mosca, aedes

**Comment by tennessine** [comment]
哦 谢谢
