### ISSUE TITLE
有没有es6版本的，mpvue里面想要引用这个不好使

### ISSUE THREAD

**Issue by AllenHom** [tennessine/paho.mqtt.wxapp#12]
引入的时候在微信小程序开发工具里面运行的时候就报错了，提示
VM2254:1 thirdScriptError 
 sdk uncaught third Error 
 Cannot assign to read only property 'exports' of object '#<Object>' 
 TypeError: Cannot assign to read only property 'exports' of object '#<Object>'

应该是webpack2不让同时使用import和module.exports的缘故

**Comment by tennessine** [comment]
还没有es6版本呢，打算重写
