### ISSUE TITLE
部署在本地测试，连接时出现失败

### ISSUE THREAD

**Issue by polyGithub** [tennessine/paho.mqtt.wxapp#2]
你好，非常感谢分享这个例程！
我用了你的例子，在本地安装了MQTT服务器，MQTT服务器通过工具测试是没有问题的。
我用你的sample例子做测试，本地MQTT服务器有响应，但建立连接失败
微信开发工具调试信息：asdebug.js:1 WebSocket connection to 'wss://192.168.1.153:1883/mqtt' failed: Error in connection establishment: net::ERR_CONNECTION_RESET
本地服务器信息
1502551781: mosquitto version 0.15 (build date 2013-08-23 19:23:43+0000) starting
1502551781: Opening ipv4 listen socket on port 1883.
1502551781: Opening ipv6 listen socket on port 1883.
1502552225: New connection from 192.168.1.2.
1502552225: Socket read error on client (null), disconnecting.

另：我用官方提供的MQTT工具测试的url连接如下：
tcp://192.168.1.153:1883
谢谢

**Comment by vikingsailor** [comment]
[在这里发现了又一个使用方法，可以试一试](https://github.com/mqttjs/MQTT.js#weapp)

**Comment by tennessine** [comment]
mosquitto、emqtt暂未实现，现在只可以连接hivemq
