### ISSUE TITLE
这个库在小程序里，用不了

### ISSUE THREAD

**Issue by xoxoj** [tennessine/paho.mqtt.wxapp#4]
小程序不支持端口号配置。。

**Comment by vikingsailor** [comment]
是的，我download下来后，也运行不了 Cannot read property 'setOnMessageArrived' of undefined

**Comment by vikingsailor** [comment]
[在这里发现了又一个使用方法，可以试一试](https://github.com/mqttjs/MQTT.js#weapp)

**Comment by tennessine** [comment]
mosquitto、emqtt暂未实现，现在只可以连接hivemq

**Comment by AdoneZ** [comment]
在connectSocket()的配置中添加 属性protocols: ['mqtt']就可以连接EMQTT了
