### ISSUE TITLE
 Error during WebSocket handshake: Unexpected response code: 404

### ISSUE THREAD

**Issue by jiangjj1993** [tennessine/paho.mqtt.wxapp#7]
Error during WebSocket handshake: Unexpected response code: 404

**Comment by tennessine** [comment]
@jiangjj1993 什么broker

**Comment by tennessine** [comment]
你连我的看能连上不 www.mengmeitong.com 端口 443 / 8883 都可以

**Comment by jiangjj1993** [comment]
var client = new Paho.Client('4things.cn',8083,"kR6HoTktVVyvATQM");
    client.connect({
      useSSL: false,
      cleanSession: true,
      keepAliveInterval: 60,
WebSocket connection to 'ws://4things.cn:8083/' failed: Error during WebSocket handshake: Unexpected response code: 404

var client = new Paho.Client('4things.cn',8083,"kR6HoTktVVyvATQM");
WebSocket connection to 'ws://4things.cn:8083/mqtt' failed: Error during WebSocket handshake: Unexpected response code: 400

android 和 ios都能连通，我想知道服务器端是否要单独为小程序做过什么配置么

**Comment by tennessine** [comment]
@jiangjj1993 小程序必须用https，上线之后必须用443端口，我的是nginx转发到8883端口的

**Comment by tennessine** [comment]
@jiangjj1993 小程序很特殊的

**Comment by tennessine** [comment]
你先用我的测试服务器试试，你们服务器用的什么? mosquitto ? emqtt? 还是什么
